### ISSUE TITLE
numpy.core._exceptions.MemoryError: Unable to allocate 4.61 GiB for an array with shape (4953037641,) and data type bool

### ISSUE THREAD

**Issue by Hardlearn** [DessimozLab/omamer#1]
Hi,

When I tried to use omamer mkdb, I got a error like this:
Traceback (most recent call last):
  File "/mnt/sdb1/home//huanghaoran/.local/bin/omamer", line 190, in <module>
    args.func(args)
  File "/mnt/sdb1/home/huanghaoran/.local/lib/python3.6/site-packages/omamer/_runners.py", line 59, in mkdb_oma
    ki.build_kmer_table()
  File "/mnt/sdb1/home/huanghaoran/.local/lib/python3.6/site-packages/omamer/index.py", line 144, in build_kmer_table
    self._build_kmer_table(sa)
  File "/mnt/sdb1/home/huanghaoran/.local/lib/python3.6/site-packages/omamer/index.py", line 304, in _build_kmer_table
    sa = sa[~sa_filter[sa]]
numpy.core._exceptions.MemoryError: Unable to allocate 4.61 GiB for an array with shape (4953037641,) and data type bool
Closing remaining open files:OMAMER_DB...done

And I also used the following solution which is doesn't work(I got the same error report):
$ cat /proc/sys/vm/overcommit_memory
0
$ sudo passwd root
$su root
$ echo 1 > /proc/sys/vm/overcommit_memory
 
I am sure I have enough memory, so how to solve this MemoryError? Thanks in advance.

Best regards.

**Comment by alex-wave** [comment]
Hello,

Thanks for your message. This error message occurs when numpy cannot allocate enough memory. Your attempted fix is altering the the virtual memory accounting mode, which I don't think will help here as we utilise the entire array. I can only think of a few explanations: 

1. you are using a 32bit version of python so are RAM-limited (I think this is extremely unlikely to be the problem and might be a windows-only limitation anyway)
2. you are in an HPC environment where you need to request extra memory
3. you don't have enough memory in your system

For the scaling experiment in the paper, we used from 5.5GB - 9GB of RAM for the build phase. I'm not sure how much we use to build a database for the full OMA release in OMAmer, but similar code in the browser uses >200GB RAM at peak to build the full suffix array + index table.

You should be able to read the maximum memory usage from a log file using the `time` command. e.g., if you run it again like this `/usr/bin/time -o omamer.log -v omamer mkdb ...` and look at `omamer.log`

Best wishes,
Alex

**Comment by alex-wave** [comment]
I'm going to close this now. If you're still experiencing problems please feel free to reopen the issue.

**Comment by Hardlearn** [comment]
thanks a lot, I already solved it.
