### ISSUE TITLE
Pip install of omamer does not lead to executable omamer

### ISSUE THREAD

**Issue by KatharinaHoff** [DessimozLab/omamer#34]
Dear developers,
I am trying to install omamer via pip in a Docker container with a python 3.10.9. I run

`pip install omamer`

The binary ends up in /opt/conda/bin/omamer, but it is not executable with the following error message:

```
Traceback (most recent call last):
  File "/opt/conda/bin/omamer", line 8, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.10/site-packages/omamer/main.py", line 33, in main
    from tables import PerformanceWarning
  File "/opt/conda/lib/python3.10/site-packages/tables/__init__.py", line 44, in <module>
    from .utilsextension import get_hdf5_version as _get_hdf5_version
  File "tables/utilsextension.pyx", line 1, in init tables.utilsextension
ValueError: numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject
```

Do you have any advice on how to fix this?

**Comment by sinamajidian** [comment]
Hi, I faced similar issue and `pip install numpy==1.23` solved it (it might need re-installing omamer).

**Comment by KatharinaHoff** [comment]
We have local machines with running older versions of omamer, but I went to one machine that does not have it, and did a pip install of omamer there, today, too, and the problem is the same. It's not a Docker problem, I tried on a native Ubuntu 22.04.4 LTS with Python 3.12.1

**Comment by alpae** [comment]
Hi @KatharinaHoff 

it seems that numpy 1.23 is too old and will be updated during the installation of omamer again to numpy==2.0.

You should rather use the latest version before 2.0.0, which is 1.26.4.

I will make a new release of omamer that freezes numpy to a pre 2.0 version in the requirements asap.

**Comment by alpae** [comment]
reference: https://github.com/PyTables/PyTables/issues/1172

**Comment by alpae** [comment]
new release 2.0.4 should fix the problem.

**Comment by KatharinaHoff** [comment]
Than you very much, indeed, this fixed the problem!
