### ISSUE TITLE
Providing an webserver of the omamer?

### ISSUE THREAD

**Issue by jinxin112233** [DessimozLab/omamer#35]
Hi~

Given that OMAmer is an improved version of OMArk, would it be a good idea to consider providing a webserver, like OMArk, to help researchers quickly try out OMAmer and evaluate how well OMAmer performs in their projects?

Best wish
XinJin

**Comment by alpae** [comment]
Hi @jinxin112233 

no, OMAmer is not an improved version of OMArk. OMAmer is a k-mer based mapper of proteomes. OMArk makes use of OMAmer to place the provided proteomes into the OMA HOGs and based on this mapping reports which parts are and which parts are not in agreement. See the paper for a detailed description:  https://doi.org/10.1038/s41587-024-02147-w
