### ISSUE TITLE
OMAmer search using all threads even when -nthreads is set

### ISSUE THREAD

**Issue by bramdanneels** [DessimozLab/omamer#4]
Hi,

I'm trying to do a OMAmer search against a prebuild database (the one for OMArk)
However, when running it automatically uses up all cores instead of the number of threads defined in -nthreads
The same problem happens when -nthreads is not defined (so should be the default 1)

Using OMAmer 0.2.2 (installed through pypi)

**Comment by alex-wave** [comment]
Hi Bram,

Thanks for letting us know about this issue.

I've found the error -- the code wasn't always calling numba.set_num_threads(nthreads) before starting to use numba parallel code.

I've fixed and tested that it now works in our environment. This fix is included in v0.2.3 that I have just released.

Please install the updated omamer package from PyPI.

If you still get this behaviour, please let us know and I'll investigate further.

Thanks,
Alex
