### ISSUE TITLE
ValueError: no field of name MedianSeqLen

### ISSUE THREAD

**Issue by mat43672** [DessimozLab/omamer#9]
Hello, first time running omamer with a fresh install, and I get this error, any clue ? Thanks

db is Metazoa

```
omamer search --log_level debug --db db.h5 --query my.species.pep.all.fa --nthreads 32 --out test
Searching: 0it [00:00, ?it/s]0 second to load query sequences
3 second to cumulate counts of reference HOGs
7 second to load the k-mer table
21 second for the actual search (~ 2 query/second)
Traceback (most recent call last):
  File "/usr/local/bin/omamer", line 190, in <module>
    args.func(args)
  File "/usr/local/lib/python3.8/dist-packages/omamer/_runners.py", line 126, in search
    df = ms.output_results(overlap=0, fst=0, sst=args.threshold, ref_taxon=args.reference_taxon)
  File "/usr/local/lib/python3.8/dist-packages/omamer/merge_search.py", line 1389, in output_results
    return pd.DataFrame(zip(*r), columns=c)
  File "/usr/local/lib/python3.8/dist-packages/pandas/core/frame.py", line 737, in __init__
    data = list(data)
  File "/usr/local/lib/python3.8/dist-packages/omamer/merge_search.py", line 1360, in <lambda>
    map(lambda x: self.hog_tab['MedianSeqLen'][x] if x != -1 else 'na', q2hog_off)]
ValueError: no field of name MedianSeqLen
Closing remaining open files:db.h5...done
```

**Comment by alpae** [comment]
Hi @mat43672 
sorry, the latest version of omamer uses an updated reference database with some additional data that wasn't collected in the initial version of omamer. I assume you either used an old `db.h5` reference database that you built with an older omamer release, or you downloaded one of the pre-built databases. In the first case, you should simply recreate the the database with `omamer mkdb ...`, in the second case you should download a newer version. However, I just realize that the newer version of the databases is not on zendoo yet...

**Comment by mat43672** [comment]
Yes I use the one from zenodo. let me know when and where I can get the new one. 
Thank you.
Mathieu

**Comment by alpae** [comment]
which one are you using. I might need to put the files somewhere else for the moment, as I don't have the rights to make a new release on zendoo.

**Comment by mat43672** [comment]
I need the Metazoa one.

**Comment by alpae** [comment]
I've uploaded the file for you here:
http://ftp.vital-it.ch/altenhoff/Metazoa.h5

this one is based on the OMA Browser release Dec 2021. To be consistent, I might regenerate the 2020 release with the new omamer version and upload that to zendoo. but I guess you don't mind having the newer (and bigger) oma release.

**Comment by mat43672** [comment]
That's perfect, it works, thank you
